services:
    n8n:
        image: docker.n8n.io/n8nio/n8n
        container_name: n8n
        restart: always
        ports:
        - 5678:5678
        environment:
        - N8N_HOST=localhost
        - N8N_PORT=5678
        - NODE_ENV=production
        - WEBHOOK_URL=http://localhost:5678
        - GENERIC_TIMEZONE=Asia/Kuala_Lumpur
        - NODEJS_PREFER_IPV4=true
        volumes:
        - n8n_data:/home/node/.n8n
        - ./local-files:/files

volumes:
  n8n_data: